name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: temurin
          java-version: 21
      - name: Build with Gradle
        run: gradle shadowJar
